package com.stylista.repository;

import com.stylista.model.CashbackAssignment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

public interface CashbackRepository extends JpaRepository<CashbackAssignment, Long> {

    List<CashbackAssignment> findByCustomerIdOrderByAssignedAtAsc(Long customerId);

    // FIFO spend order: soonest-expiring first (single customer)
    List<CashbackAssignment> findByCustomerIdOrderByExpiresAtAsc(Long customerId);

    // ── Shared-by-number pool queries ──
    // All cashbacks for a SET of customer IDs (all names on one mobile), oldest-assigned first
    List<CashbackAssignment> findByCustomerIdInOrderByAssignedAtAsc(Collection<Long> customerIds);

    // Same pool but soonest-expiring first (for FIFO spending)
    List<CashbackAssignment> findByCustomerIdInOrderByExpiresAtAsc(Collection<Long> customerIds);

    // cashback(s) generated by a given order
    List<CashbackAssignment> findByOrderId(Long orderId);

    @Query("SELECT c FROM CashbackAssignment c WHERE c.redeemed = false AND c.expiresAt > :now")
    List<CashbackAssignment> findActive(@Param("now") LocalDateTime now);

    @Query("SELECT c FROM CashbackAssignment c WHERE c.redeemed = false AND c.expiresAt > :now AND c.expiresAt <= :in7")
    List<CashbackAssignment> findExpiringSoon(@Param("now") LocalDateTime now, @Param("in7") LocalDateTime in7);

    @Query("SELECT c FROM CashbackAssignment c WHERE c.redeemed = false AND c.expiresAt > :now")
    List<CashbackAssignment> findAllActive(@Param("now") LocalDateTime now);

    long countByRedeemedFalseAndExpiresAtAfter(LocalDateTime now);
    long countByRedeemedTrue();
}
